Feature/auto index
frictionlessdata/tableschema-sql-py pull request #35
Opened 2016-08-29 12:36 UTC by akariv

I made this modification to allow creation of indexes on specific columns while creating tables.

Please let me know what you think.

2016-11-01 16:49 UTC, pwalsh commented on jsontableschema_sql/storage.py
> +    def create(self, table, schema, indexes_fields = []):
maybe a `tuple` or `None`?

2016-11-01 16:50 UTC, pwalsh commented on jsontableschema_sql/storage.py
> +    def create(self, table, schema, indexes_fields = []):
because of mutable default value....

2016-11-01 17:04 UTC, roll commented on jsontableschema_sql/storage.py
> +    def create(self, table, schema, indexes_fields = []):
After you've proposed to move default arguments to signature in GT (also I've done it in tabulator) I do opposite - all default in signatures and for mutable one I use `copy` on assignment to clear it.

2016-11-01 18:21 UTC, pwalsh commented on jsontableschema_sql/storage.py
> +    def create(self, table, schema, indexes_fields = []):
@roll I still don't see a case to use `list` and not `tuple`.

2016-11-03 15:26 UTC, roll commented
@akariv 
Sorry I've totally misunderstood the scope of this PR at first place. Thought it's about Storage API instead of just feature for SQL driver. And it requires some massive time to work on it thru the whole stack.

It seems pretty solid. One things - `indexes_fields` vs `index_fields` vs `indexes`? Last option could be later used to provide not only names but also `sqlalchemy.schema.Index` instances to provide more flexibility.

Would you like me to reabase by myself to try to heal the :broken_heart:?

2016-11-18 14:03 UTC, akariv commented on jsontableschema_sql/storage.py
> +    def create(self, table, schema, indexes_fields = []):
Note that this is a deviation from the Tabular Storage API - even though it's an optional parameter.
Perhaps we should consider a more generic method of passing driver-specific parameters in the API instead of the way I chose.

2016-11-29 16:16 UTC, akariv commented
@roll ready for review

2016-12-01 18:46 UTC, roll commented
Im on it. Will finish tomorrow morning

2016-12-02 10:20 UTC, roll requested changes
Looks good. Added a few comments. Also build is failing.

2016-12-02 10:20 UTC, roll commented on jsontableschema_sql/storage.py
> +    def __init__(self, engine, dbschema=None, prefix='', only=None):
Could we use more descriptive argument name?

2016-12-02 10:20 UTC, roll commented on jsontableschema_sql/storage.py
> +    def reflect(self):
Please move it to private methods if it's internal.

2016-12-02 21:26 UTC, akariv commented on jsontableschema_sql/storage.py
> +    def reflect(self):
done

2016-12-02 21:27 UTC, akariv commented on jsontableschema_sql/storage.py
> +    def __init__(self, engine, dbschema=None, prefix='', only=None):
done

2016-12-04 15:19 UTC, akariv commented
@roll ready for re-review

2016-12-05 09:14 UTC, roll approved these changes
:+1:

2016-12-05 09:33 UTC, merged